### ISSUE TITLE
All tests will fail by default on Rails 6 with default configuration

### ISSUE THREAD

**Issue by ceslami** [Betterment/webvalve#29]
The [default Gemfile](https://raw.githubusercontent.com/railsdiff/api/master/generated/v6.0.0.rc1/Gemfile) for Rails 6 apps (as of `6.0.0rc1`) replaces `chromedriver-helper` with the `webdrivers` gem. The `chromedriver-helper` gem is deprecated in favor of `webdrivers`.

`webdrivers` is useful because it dynamically downloads and caches the correct version of Chrome, for example, based on the version you've installed on your local machine. It supports the other drivers you can use with Selenium, too. It does this at test execution time (importantly, with `RAILS_ENV=test`).

`webvalve` disallows the driver download because non-localhost HTTP requests are disallowed in the test environment, regardless of whether the developer uses `.whitelist_url` in her `webvalve.rb` file. The resulting error looks like:

```
WebMock::NetConnectNotAllowedError:
            Real HTTP connections are disabled. Unregistered request: GET https://chromedriver.storage.googleapis.com/ with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Host'=>'chromedriver.storage.googleapis.com', 'User-Agent'=>'Ruby'}

            You can stub this request with the following snippet:

            stub_request(:get, "https://chromedriver.storage.googleapis.com/").
              with(:headers => {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Host'=>'chromedriver.storage.googleapis.com', 'User-Agent'=>'Ruby'}).
              to_return(:status => 200, :body => "", :headers => {})
```

How does `webvalve` want to deal with this new reality? Any developer can solve this by hand-writing a call to `Webmock.disable_net_connect!` with well-crafted proc passed as the `allow:` parameter, somewhere in the test configuration for their testing library. At minimum, should we update the docs to let folks using Rails 6+ know that they'll need to do so? Should allowing access to the remote driver repository be a responsibility of `webvalve` (or a sister gem for consumers who use rails?)?

Mostly, just an FYI!

**Comment by samandmoore** [comment]
@ceslami what do you think would be the best developer experience?

it wouldn't be _that hard_ to do a conditional on the presences of the `Webdrivers` constant that iterates over each of the constants in that namespace that has a `base_url` and whitelist's that url. That's not ideal because of the tight coupling to the `webdrivers` gem, but maybe it's fine if that gem is fairly stable?

**Comment by samandmoore** [comment]
we could do something like this

```ruby
webdriver_download_urls = Webdrivers.constants.map { |c| Webdrivers.const_get(c) }.map { |c| c.send(:base_url) if c.respond_to?(:base_url, true) }.compact
webdriver_download_urls.each { |url| Webvalve.whitelist_url(url) }
```

**Comment by xyingsoft** [comment]
Webvalve designed whitelist doesn't work in test environment. I think whitelist should work in all environment - #31

**Comment by ceslami** [comment]
@samandmoore and I have had some conversations about this. The crux of the issue is whether we want to make is `webvalve`-proper's business that Rails, by way of `webdrivers`, has a need to make HTTP requests in the test lifecycle.

We came to the conclusion (and please correct me, @samandmoore!) that this is in fact not a Rails-specific issue. If we can make `webvalve` aware of burgeoning _Ruby_ community conventions in a way that doesn't compromise the core philosophies of `webvalve`, that would be fine. Specifically, this means making sure that whitelist URLs configured in application-space (ie `webvalve.rb`) only apply in development, while using the whitelisting facility of the gem to allow `webdrivers` to work correctly in tests.

Curious to know if you're aligned on this too, @jmileham @smudge. Assuming there's alignment, the question of whether we want to accommodate Rails, or Ruby apps in general, informs where we'd put the code that @samandmoore sampled above.
