### ISSUE TITLE
Rubygem packages have incorrect file permissions

### ISSUE THREAD

**Issue by aburgel** [Betterment/webvalve#70]
I ran into an issue where webvalve was not loading at all. In my Rails app, my fake services were not getting invoked, and when I manually loaded webvalve via `require "webvalve"`, I would get a `LoadError`. It turns out the issue had to do with file permissions.

Some of the files in the gem package are readable by the owner only, so if you install gems with one user and run your app with another, the files will not be readable.

These are the permissions of the files in the gem downloaded from rubygems.
```bash
> ls -al webvalve-2.0.1/data/lib
total 8
drwxr-xr-x@  5 aburgel  staff   160 Jun  9 22:17 .
drwx------@  8 aburgel  staff   256 Jun  9 22:17 ..
drwxr-xr-x@  3 aburgel  staff    96 Jun  9 22:17 generators
drwxr-xr-x@ 13 aburgel  staff   416 Jun  9 22:17 webvalve
-rw-------@  1 aburgel  staff  1818 May 21 13:15 webvalve.rb
```

The permissions go bad starting with 1.3.0. In 1.2.0, they are correct.
```bash
> ls -al webvalve-1.2.0/data/lib
total 8
drwxr-xr-x@  5 aburgel  staff   160 Jun 10 09:36 .
drwx------@  8 aburgel  staff   256 Jun 10 09:36 ..
drwxr-xr-x@  3 aburgel  staff    96 Jun 10 09:36 generators
drwxr-xr-x@ 12 aburgel  staff   384 Jun 10 09:36 webvalve
-rw-r--r--@  1 aburgel  staff  1818 Dec 16  2021 webvalve.rb
```

FWIW, I'm a big fan of webvalve. You all do great work! ❤️

**Comment by smudge** [comment]
Oh hey! Well, glad you're a fan. 😉 

I can confirm that I see `-rw-------` in my bundler-managed install, but a fresh clone yields `.rw-r--r--`, so it's likely an issue with the publish step. Chatting internally, but I imagine we can cut a new release off a fresh git clone and see if that fixes the issue for you.

**Comment by aburgel** [comment]
That fixes it. Thanks for the quick turnaround 😄
